### ISSUE TITLE
Empty list as default argument of function

### ISSUE THREAD

**Issue by mpvanderschelling** [bessagroup/f3dasm_simulate#3]
https://github.com/bessagroup/f3dasm_simulate/blob/1ae25bcff81cef6de3c4c71fdcbd744a497130ba/src/f3dasm_simulate/openFoam/openfoam_simulator.py#L100-L101

Dont use mutable default arguments. This is will result to unexpected behaviour. Better is to set the default to None and then check with an if-statement, and if true create an empty list

**Comment by GuillaumeBroggi** [comment]
Thanks for the hint! Now corrected.
