### ISSUE TITLE
what happens when the solver != auto ? Maybe create else case

### ISSUE THREAD

**Issue by mpvanderschelling** [bessagroup/f3dasm_simulate#4]
https://github.com/bessagroup/f3dasm_simulate/blob/1ae25bcff81cef6de3c4c71fdcbd744a497130ba/src/f3dasm_simulate/openFoam/openfoam_simulator.py#L105

**Comment by GuillaumeBroggi** [comment]
If the solver is not `auto`, it means that is was specified and as `solver` is used later out of the if statement, the logic can continue.

Unfortunately, the list of available solver is not fixed so it is not possible to check for the existence of the solver (at least not trivially).
