### ISSUE TITLE
don't you mean to raise an Exception here instead of setting an attribute ?

### ISSUE THREAD

**Issue by mpvanderschelling** [bessagroup/f3dasm_simulate#5]
https://github.com/bessagroup/f3dasm_simulate/blob/1ae25bcff81cef6de3c4c71fdcbd744a497130ba/src/f3dasm_simulate/openFoam/openfoam_simulator.py#L175-L179

**Comment by GuillaumeBroggi** [comment]
Yes! But should we rise an exception or just log an error to f3dasm? 
For a large Doe, a blockMesh issue is likely to happen in edge cases. An exception might interrupt the run.

**Comment by GuillaumeBroggi** [comment]
Now both logging the issue and raising an exception.
