### ISSUE TITLE
raise an exception if allclean_path is not a file

### ISSUE THREAD

**Issue by mpvanderschelling** [bessagroup/f3dasm_simulate#7]
https://github.com/bessagroup/f3dasm_simulate/blob/1ae25bcff81cef6de3c4c71fdcbd744a497130ba/src/f3dasm_simulate/openFoam/openfoam_simulator.py#L154-L156

**Comment by GuillaumeBroggi** [comment]
This piece of code is no longer required as the functionality is implemented in `PrepareCase` form `PyFoam`.
